### ISSUE TITLE
Broken syntax highlithing on comments

### ISSUE THREAD

**Issue by Eragonfr** [nonetallt/vim-neon-dark#2]
Hi, it's me again.
I'm using the 2.0 tag for this theme and using [tree-sitter-comment](https://github.com/stsewd/tree-sitter-comment) to parse comments.
But I have this weird bugged comments highlight.
![image](https://user-images.githubusercontent.com/28783835/224175307-e2979ad0-91b5-413d-ac38-caa4966a195c.png)
From what I understand this file should have some form of highlight on each line except the last one which is a modeline to force the file type to be parsed by tree-sitter-comment.

I think there are some missing colours for the `XXX`, `FIXME` and other keywords. What I don't understand is why the `TODO` is highlighted but not the others.

This :
```comment
FIXME(Eragon): this is a comment
XXX: This too
TODO: This one works
TODO: something needs to be done
TODO(stsewd): something needs to be done by @stsewd

XXX: fix something else.
XXX:    extra white spaces.

(NOTE: this works too).

NOTE-BUG (stsewd): tags can be separated by `-`
NOTE_BUG: or by `_`.
```
Should give that
```tree-sitter
source [0, 0] - [15, 0]
  tag [0, 0] - [0, 14]
    name [0, 0] - [0, 5]
    user [0, 6] - [0, 12]
  tag [1, 0] - [1, 4]
    name [1, 0] - [1, 3]
  tag [2, 0] - [2, 5]
    name [2, 0] - [2, 4]
  tag [3, 0] - [3, 5]
    name [3, 0] - [3, 4]
  tag [4, 0] - [4, 13]
    name [4, 0] - [4, 4]
    user [4, 5] - [4, 11]
  tag [6, 0] - [6, 4]
    name [6, 0] - [6, 3]
  tag [7, 0] - [7, 4]
    name [7, 0] - [7, 3]
  tag [9, 1] - [9, 6]
    name [9, 1] - [9, 5]
  tag [11, 0] - [11, 18]
    name [11, 0] - [11, 8]
    user [11, 10] - [11, 16]
  tag [12, 0] - [12, 9]
    name [12, 0] - [12, 8]
```
based on the playground at https://stsewd.dev/tree-sitter-comment/

I think the missing colour is `comment.tag.name` or something like that. I don't really understand how this works.

**Comment by nonetallt** [comment]
It looks like https://github.com/stsewd/tree-sitter-comment doesn't come with any highlight queries, hence it does the tree-sitter parsing as expected but doesn't provide any highlights by default. As for the `TODO`, it's a string literal that's provided by the core nvim-treesitter queries. The capture group is called [@text.todo](https://github.com/nvim-treesitter/nvim-treesitter/blob/cfa9b70ee85f9ead92c691cbc0b134a441864080/queries/comment/highlights.scm#L4).

For debugging, you can use the `:TSPlaygroundToggle` to show playground in the editor and then press `i` in the playground window to display the highlight capture groups:

![comment_highlights](https://user-images.githubusercontent.com/22174322/224307035-793c1f1a-b25a-4e28-9e22-c80833a7e1ac.png)

In any case it shouldn't be too much of a hassle adding the capture groups.

**Comment by nonetallt** [comment]
Here's what I managed without overriding any core groups:

![comment_highlights_5](https://user-images.githubusercontent.com/22174322/224371277-88775f61-cefd-4b03-ac45-6aa8f40a6529.png)

The core treesitter highlights provide the following:
- @text.todo       (TODO)
- @text.note       (NOTE or XXX)
- @text.danger   (FIXME or BUG)
- @text.warning  (HACK or WARNING)

I extended `@text.note` group to include comment tags starting with NOTE. Using the constant group for user names is somewhat of a compromise since it's not necessarily the best fit but it works with the treesitter defaults without extensive changes.

Feel free to give feedback or suggestions, especially regarding the colors. I don't really have a good reference for comment colors from the parent theme. In general, I try to avoid using the more flashy colors in comments (besides the attention colors for danger and warning) since there's already a lot going on on the screen and comments aren't really meant to be syntactic in the first place.

**Comment by Eragonfr** [comment]
The blue over yellow feel strange, but that may be my personal preference.

> For debugging, you can use the :TSPlaygroundToggle to show playground in the editor and then press i in the playground window to display the highlight capture groups:

Thanks for the info.

The Sublime Theme have support for comments only in python here is an example of that.
![image](https://user-images.githubusercontent.com/28783835/224374979-ead2166c-547e-4973-97ab-e149b9f26c35.png)

I think the blue background is distracting, and the red/magenta should be modified to better reflect the comment. Also having the rest of the comment in yellow is probably not possible.

If I follow my personal preferences
The light color on `BAR` and `FOO-NOTE` could be applied to @text.note
The yellow text with black background that you have on @text.note on your picture could be moved to @text.todo
Maybe the orange and the red should be on the text instead of being on the background.

**Comment by nonetallt** [comment]
@Eragonfr 

How about something like this:

![comment_highlights_7](https://user-images.githubusercontent.com/22174322/224385079-3bb598f5-53ed-4deb-a9b1-7fc6d24bd914.png)

The reason I changed the blue-grey to purple-grey is because the the former is currently used for types while the new purple colors are only used for phpdoc comments. Also changed the `@comment.tag.user` from red to dark purple to avoid mixing it with what are interpreted as constants by treesitter.

**Comment by Eragonfr** [comment]
This is great, and seems perfect.

Also, maybe unrelated.
I guess I'm missing some configuration but I don't have a capture group on `FOO-NOTE` and `BAR` did you modify something ?

**Comment by nonetallt** [comment]
> I guess I'm missing some configuration but I don't have a capture group on FOO-NOTE and BAR did you modify something ?

I didn't push any changes yet. `FOO-NOTE` and `BAR` are provided by new capture groups I made for `tree-sitter-comment`, since the repo doesn't provide any captures. The other groups are provided by treesitter core but were previously lacking highlight definitions (they had groups. just no colors to match those groups in this theme).

Will release changes as version `2.1.0`.

**Comment by Eragonfr** [comment]
Thanks a lot
